services:

  # iNvent API Service
  invent-api:
    build: .
    container_name: invent_api # Nombre del container para NPM
    restart: unless-stopped
    environment:
      DB_URL: "jdbc:postgresql://postgres_db:5432/inventory_db"
      DB_USER: admin
      DB_PASSWORD: 1234admin6789
    depends_on:
      - postgres
    networks:
      - proxy-network # Red para conectar con el proxy inverso

  # PostgreSQL Database Service
  postgres:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234admin6789
      POSTGRES_DB: inventory_db
    ports:
      - "127.0.0.1:5432:5432" # Puerto solo para acceso local/docker network
    volumes:
      - postgres_data:/var/lib/postgresql # en la versión 18 ha cambiado, la ruta a /data ahora es automática
    networks:
      - proxy-network

  # Adminer Database Management UI Service
  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8083:8080" # Puerto solo para acceso local/docker network
    depends_on:
      - postgres
#    networks:
#      - proxy-network # Red para el proxy inverso

volumes:
  postgres_data:

networks:
  proxy-network:
    external: true

# Para correr los servicios:
# Primero se levanta la red:
  # 1- docker network create proxy-network
# Luego se levanta este docker compose con la API y la base de datos:
  # 2- docker compose up -d --build
# Para ver los servicios activos
  # 3- docker compose ps
# Para acceder a Adminer: http://localhost:8083 o por proxy inverso si se habilita un puerto al exterior
# Para parar los servicios:
  # docker compose down -v