services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234admin6789
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # en la versión 18 ha cambiado, la ruta a /data ahora es automática

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: unless-stopped
    ports:
      - "8083:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
