services:
  # PostgreSQL Database Service
  postgres:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234admin6789
      POSTGRES_DB: inventory_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # en la versión 18 ha cambiado, la ruta a /data ahora es automática
  # Adminer Database Management UI Service
  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8083:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

# Para correr los servicios:
# docker compose up -d
# Para ver los servicios activos
# docker compose ps
# Para acceder a Adminer: http://localhost:8083
# Para parar los servicios:
# docker compose down -v